http:
  routers:
    plex:
      rule: "Host(`plex.local.aydenjahola.com`)"
      entryPoints:
        - "https"
      middlewares:
        - "plexHeaders"
      service: "plex"
    truenas:
      rule: "Host(`truenas.local.aydenjahola.com`)"
      entryPoints:
        - "https"
      service: "truenas"
    nomad:
      rule: "Host(`nomad.local.aydenjahola.com`)"
      entryPoints:
        - "https"
      middlewares:
        - "nomadHeaders"
      service: "nomad"
    radarr:
      rule: "Host(`radarr.local.aydenjahola.com`)"
      entryPoints:
        - "https"
      service: "radarr"
    sonarr:
      rule: "Host(`sonarr.local.aydenjahola.com`)"
      entryPoints:
        - "https"
      service: "sonarr"
    prowlarr:
      rule: "Host(`prowlarr.local.aydenjahola.com`)"
      entryPoints:
        - "https"
      service: "prowlarr"
    qbittorrent:
      rule: "Host(`torr.local.aydenjahola.com`)"
      entryPoints:
        - "https"
      service: "qbittorrent"
    netdata:
      rule: "Host(`nasstatus.local.aydenjahola.com`)"
      entryPoints:
        - "https"
      service: "netdata"
  services:
    plex:
      loadBalancer:
        servers:
          - url: "http://192.168.1.56:32400"
    truenas:
      loadBalancer:
        servers:
          - url: "http://192.168.1.52:80"
    nomad:
      loadBalancer:
         servers:
          - url: "http://192.168.1.34:4646"
    radarr:
      loadBalancer:
         servers:
          - url: "http://192.168.1.14:7878"
    sonarr:
      loadBalancer:
         servers:
          - url: "http://192.168.1.14:8989"
    prowlarr:
      loadBalancer:
         servers:
          - url: "http://192.168.1.52:9696"
    qbittorrent:
      loadBalancer:
        servers:
          - url: "http://192.168.1.8:8080"
    netdata:
      loadBalancer:
         servers:
          - url: "http://192.168.1.52:19999"
  middlewares:
    plexHeaders:
      headers:
        sslRedirect: true
        stsSeconds: "315360000"
        browserXSSFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: false
    nomadHeaders:
      headers:
        customRequestHeaders:
          Origin: "https://nomad.local.aydenjahola.com"
