api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
          permanent: true
  https:
    address: ":443"
    http:
      tls:
        certresolver: cloudflare
        domains:
          - main: "aydenjahola.com"
            sans: "*.aydenjahola.com"
          - main: "local.aydenjahola.com"
            sans: "*.local.aydenjahola.com"

certificatesResolvers:
  cloudflare:
    acme:
      storage: "acme.json"
      dnsChallenge:
        provider: "cloudflare"
        delayBeforeCheck: 90
        disablePropagationCheck: true
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    watch: true
    network: "proxy"
    exposedbydefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: "traefik_dynamic.yml"
  nomad:
    endpoint:
      address: "http://192.168.1.34:4646"

