version: '3.5'

services:
  dash:
    container_name: dashdot
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
    volumes:
      - /:/mnt/host:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashdot.entrypoints=https"
      - "traefik.http.routers.dashdot.rule=Host(`dashdot.local.aydenjahola.com`)"
      - "traefik.http.services.dashdot.loadbalancer.server.port=3001"
    networks:
      - proxy

networks:
  proxy:
    external: true
