version: '3'
services:
  nginx:
    container_name: java-website
    image: nginx:latest
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.java.entrypoints=https"
      - "traefik.http.routers.java.rule=Host(`java.aydenjahola.com`)"
    networks:
      - proxy

networks:
  proxy:
    external: true
