version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ~/homelab-data/uptime-kuma-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.entrypoints=https"
      - "traefik.http.routers.uptimekuma.rule=Host(`monitor.aydenjahola.com`)"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
    networks:
      - proxy

networks:
  proxy:
    external: true
